name: Shoe Checker Every 10 Min

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch: 

jobs:
  check-shoes:
    runs-on: ubuntu-latest

    env:
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          # Install required libraries for Selenium and Chrome
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo apt-get install -y libx11-xcb1 libgbm1 libxcomposite1 libxdamage1 libxi6 libxrandr2
          sudo apt-get install -y libnss3 libgdk-pixbuf2.0-0
          
          # Install Python dependencies
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Restore cached shoes.json
        uses: actions/cache@v4
        with:
          path: |
            shoes.json
            shoes_log.csv
          key: shoes-data

      - name: Run shoe checker
        run: python main.py

      - name: Upload shoe logs
        uses: actions/upload-artifact@v4
        with:
          name: shoe-logs
          path: |
            shoes.json
            shoes_log.csv
